flask_app/search/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user

from .. import product_client
from ..forms import BrandFilterForm, SearchForm, TypeFilterForm
from ..models import User

search = Blueprint('search', __name__)

@search.route("/", methods=["GET", "POST"])
def index():

    query = SearchForm()
    brandForm = BrandFilterForm()
    typeForm = TypeFilterForm()

    if query.validate_on_submit():
        product_client.search(query.search_query.data.lower())

    return render_template(
        "index.html", query = query, brandForm = brandForm, 
        typeForm = typeForm, products = product_client.data
    )

@search.route("/filter", methods=["GET", "POST"])
def filter():
    brandForm = BrandFilterForm()
    typeForm = TypeFilterForm()
    
    if brandForm.validate_on_submit():
        brand = brandForm.selection.data
        product_type = []

        product_client.filter(brand, product_type)

    if typeForm.validate_on_submit():
        brand = []
        product_type = typeForm.selection.data

        product_client.filter(brand, product_type)

    return redirect(url_for("search.index"))

@search.route("/show_all", methods=["GET", "POST"])
def show_all():
    product_client.get_all()

    return redirect(url_for("search.index"))

@search.route("/description", methods=["GET", "POST"])
def description():
    return render_template("description.html")

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_mail import Message
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.utils import secure_filename
import io
import base64
import face_recognition
import math
from PIL import Image

from .. import bcrypt, product_client
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User

users = Blueprint('users', __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("search.index"))

    form = RegistrationForm()

    if form.validate_on_submit():
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username = form.username.data, email = form.email.data, password = pass_hash)
        user.save()

        return redirect(url_for("users.login"))

    return render_template("register.html", title = "Register", form = form)

@users.route("/login", methods = ["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("search.index"))
    
    form = LoginForm()

    if form.validate_on_submit():
        user = User.objects(username = form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("search.index"))
        else:
            flash("Login failed. Verify your username and password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title = "Login", form = form)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("search.index"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    userForm = UpdateUsernameForm()
    profileForm = UpdateProfilePicForm()

    user = User.objects(username = current_user.get_id()).first()

    if userForm.validate_on_submit():
        try:
            userForm.validate_user(userForm.username.data)

            user.modify(username = userForm.username.data)
            user.save()
        except Exception:
            flash("Username is taken")
    
        return redirect(url_for('users.account'))
    
    if profileForm.validate_on_submit():
        img = profileForm.picture.data
        filename = secure_filename(img.filename)
        content_type = f'images/{filename[-3:]}'

        image = face_recognition.load_image_file(img)
        face_locations = face_recognition.face_locations(image)
        
        if len(face_locations) > 1:
            flash("Please enter a picture with only you inside")
        else:
            face_location = face_locations[0]
            top, right, bottom, left = face_location
            face_image = image[top:bottom, left:right]
            pil_image = Image.fromarray(face_image)
            pix = pil_image.load()
            (x_max, y_max) = pil_image.size
            cumulative = 0

            for i in range(0, x_max):
                for j in range(0, y_max):
                    (x, y, z) = pix[i,j]
                    cumulative += math.sqrt(x**2 + y**2 + z**2)

            average = cumulative / (x_max * y_max)

            recs = product_client.get_best_color(average)

            """if user.skin_value is None:
                user.skin_value = average
            else:
                user.modify(skin_value = average)"""

            user.modify(skin_value = average, rec_products = recs)     

        if user.profile_pic.get() is None:
            user.profile_pic.put(img.stream, content_type = content_type)
        else:
            user.profile_pic.replace(img.stream, content_type = content_type)

        user.save()

        return redirect(url_for('users.account'))

    return render_template("account.html", userForm=userForm, picForm=profileForm, image = get_b64_img(user.username))

@users.route("/add_likes", methods=["GET", "POST"])
@login_required
def add_likes():
    user = User.objects(username = current_user.get_id()).first()

    if request.method == 'POST':
        product_id = request.form.get('LIKE')
        likes = user.liked_products

        if likes is None:
            user.modify(liked_products = [product_id])
        else:
            likes.append(product_id)
            user.modify(liked_products = likes)

    return redirect(url_for("search.index"))

@users.route("/likes", methods=["GET", "POST"])
@login_required
def likes():
    user = User.objects(username = current_user.get_id()).first()
    ids = user.liked_products

    result = product_client.get_by_id(ids = ids)

    return render_template(
        "likes.html", products = result
    )

@users.route("/recommended", methods=["GET", "POST"])
@login_required
def recommended():
    user = User.objects(username = current_user.get_id()).first()
    ids = user.rec_products

    result = product_client.get_by_id(ids = ids)

    return render_template(
        "recommended.html", products = result
    )

def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {# Profile picture #}
        <img class="propic w-50" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        {# Greeting #}
        <h3>Hello, {{ current_user.username }}</h3>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Username Update Form #}

        <div class="container">
            <form method="POST" action="">
                {{ userForm.csrf_token }}
                <div class="form-group">
                    {{ userForm.username.label }}
                    {{ userForm.username(class="form-control") }}
                </div>

                {% if userForm.username.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in userForm.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}

                {{ userForm.submit() }}
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        {# Profile Picture Update Form #}

        <div class="container">
            <form method="POST" action="" enctype="multipart/form-data">
                {{ picForm.csrf_token }}
                <div class="form-group">
                    {{ picForm.picture }}
                </div>
                
                {% if picForm.picture.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in picForm.picture.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}

                {{ picForm.submit() }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap Dependencies -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <!-- Styling Dependencies -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">

    <style>
        .center {
            text-align: center;
        }

        .product_pics {
            max-width: 200px;
            max-height: 200px;
            height: auto;
            width: auto;
        }

        .propic {
            max-width: 50%;
        }
    </style>

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Style Guide</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Will be overriden</h1>
    {% endblock %}

    <!-- Footer -->
    <div class="jumbotron text-center" style="margin-bottom:0px; background-color:#d5befa; font-family:'Poppins',sans-serif; font-size:15px;"> 
        <footer>
            <p>Styles, Copyright &copy; 2020</p>
            <a id="top-of-page" href="#">Top</a>
        </footer>
    </div>

    <!--
    {% block footer %}
    <h1>Will be overriden</h1>
    {% endblock %}
    -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/description.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Group Members: Caleb Wheeler</h2>
        <p>
            This project is a makeup shopping app that uses the Heroku Makeup 
            API in order to list at set of offerings to the user. It contains
            a system to filter shopping option, a system to like and save products,
            and a system for getting makeup recommendations based on skin color
            when a user uploads a photo.
        </p>
    </div>
</div>

{% endblock %}

flask_app/templates/footer.html
{% extends "base.html" %}
{% block footer %}

<!-- Footer -->
<div class="jumbotron text-center" style="margin-bottom:0px; background-color:#d5befa; font-family:'Poppins',sans-serif; font-size:15px;"> 
    <footer>
        <p>Styles, Copyright &copy; 2020</p>
        <a id="top-of-page" href="#">Top</a>
    </footer>
</div>

{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('search.index') }}">Styles</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('search.description') }}">
                    Description
                </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.likes') }}">
                    Likes
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.recommended') }}">
                    Recommended
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {{ query.csrf_token }}
            {{ query.search_query(class="form-control", placeholder="Search") }}

            {% if query.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in query.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ query.submit(class="btn btn-outline-success") }}
        </form>
    </div>
</div>

<div class="container">
    <div class="row">
        <form action="/filter" method="POST">

            {{ brandForm.csrf_token }}
            
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Filter Brand
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {{ brandForm.selection.label }} {{ brandForm.selection(rows = 57, multiple = True) }}
                </div>
            </div>

            {{ brandForm.submit() }}
        </form>
        <form action="/filter" method="POST">

            {{ typeForm.csrf_token }}

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Filter Category
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    {{ typeForm.selection.label }} {{ typeForm.selection(rows = 10, multiple = True) }}
                </div>
            </div>

            {{ typeForm.submit() }}
        </form>
    </div>
    <form method="POST" action="/show_all">
        <button type="submit" value="">Show All</button>
    </form>
</div>

<div class="container-fluid">
    <div class="row">
        {% for product in products %}
            <div class="col-md-12">
                <div class="center">
                    <img alt="Image not found" src="{{ product['image_link'] }}" class="rounded-circle product_pics w-50">
                    <h3>
                        {{ product['name'] }}
                    </h3>
                    <button class="btn btn-success" id="modal-{{ product['id'] }}" data-toggle="modal" data-target="#modal-container-{{ product['id'] }}">
                        Get Details
                    </button>

                    {% if current_user.is_authenticated %}
                    <form method="POST" action="/add_likes">
                        <button type="submit" name="LIKE" value="{{ product['id'] }}">LIKE</button>
                    </form>
                    {% endif %}
                </div>

                <div class="modal fade" id="modal-container-{{ product['id'] }}" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel">
                                    {{ product['name'] }}
                                </h5> 
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <b>{{ product['brand'] }}</b>
                                <p><b>Description:</b> {{ product['description'] }}</p>
                                <p><b>Type:</b> {{ product['product_type'] }}</p>
                                <p><b>Price:</b> ${{ product['price'] }}</p>
                                <b>Product Link: </b><a href="{{ product['product_link'] }}">{{ product['product_link'] }}</a>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

flask_app/templates/likes.html
{% extends "header.html" %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        {% for product in products %}
            <div class="col-md-12">
                <div class="center">
                    <img alt="Image not found" src="{{ product['image_link'] }}" class="rounded-circle product_pics w-50">
                    <h3>
                        {{ product['name'] }}
                    </h3>
                    <button class="btn btn-success" id="modal-{{ product['id'] }}" data-toggle="modal" data-target="#modal-container-{{ product['id'] }}">
                        Get Details
                    </button>
                </div>

                <div class="modal fade" id="modal-container-{{ product['id'] }}" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel">
                                    {{ product['name'] }}
                                </h5> 
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <b>{{ product['brand'] }}</b>
                                <p><b>Description:</b> {{ product['description'] }}</p>
                                <p><b>Type:</b> {{ product['product_type'] }}</p>
                                <p><b>Price:</b> ${{ product['price'] }}</p>
                                <b>Product Link: </b><a href="{{ product['product_link'] }}">{{ product['product_link'] }}</a>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}

<div class="col">
    Do you have an account? If not, register <a href="{{ url_for('users.register') }}">here!</a>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            <div class="center">
                <img alt="No Image Available" src="https://www.birchgrovedental.co.uk/wp-content/uploads/2016/01/empty-person.jpg" class="rounded-circle" />
            </div>

            <h3>
                Login
            </h3>

            <form action="" method="post">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.username.label(class="form-control-label green-text") }}
                    {{ form.username(class="form-control form-control-md") }}
    
                    {% if form.username.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control form-control-lg") }}
    
                    {% if form.password.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.submit(class="form-control form-control-lg") }}
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

flask_app/templates/recommended.html
{% extends "header.html" %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        {% for product in products %}
            <div class="col-md-12">
                <div class="center">
                    <img alt="Image not found" src="{{ product['image_link'] }}" class="rounded-circle product_pics w-50">
                    <h3>
                        {{ product['name'] }}
                    </h3>
                    <button class="btn btn-success" id="modal-{{ product['id'] }}" data-toggle="modal" data-target="#modal-container-{{ product['id'] }}">
                        Get Details
                    </button>
                </div>

                <div class="modal fade" id="modal-container-{{ product['id'] }}" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel">
                                    {{ product['name'] }}
                                </h5> 
                                <button type="button" class="close" data-dismiss="modal">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <b>{{ product['brand'] }}</b>
                                <p><b>Description:</b> {{ product['description'] }}</p>
                                <p><b>Type:</b> {{ product['product_type'] }}</p>
                                <p><b>Price:</b> ${{ product['price'] }}</p>
                                <b>Product Link: </b><a href="{{ product['product_link'] }}">{{ product['product_link'] }}</a>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    Close
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already have an account, then just <a href="{{ url_for('users.login') }}">Log In!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}